export const TASK_UI_TEXT = {
    BOARD_TITLE: "Gestión de tareas",
    FORM_TITLE: "Agregar nueva tarea",
    INPUT_PLACEHOLDER: "Escribe el título de la tarea...",
    ADD_BUTTON: "Agregar tarea",
    TASK_LIST_TITLE: "Lista de tareas",
    TASK_LIST_EMPTY: "No hay tareas disponibles.",
    INPUT_LABEL: "Título de la tarea",
    TASK_STATE_COMPLETE: "Completa",
    TASK_STATE_INCOMPLETE: "Incompleta",
    DELETE_BUTTON: "Eliminar",
    FILTER_ALL: "Todas",
    FILTER_PENDING: "Pendientes",
    FILTER_COMPLETED: "Completadas",
    FILTERS_TITLE: "Filtros",
    FILTERS_SEARCH_PLACEHOLDER: "Buscar tareas...",
} as const;